services:
  ensek.servicehost.consumermeterdataservice:
    image: ensek.servicehost.consumermeterdataservice
    build:
      context: .
      dockerfile: Ensek.ServiceHost.ConsumerMeterDataService/Dockerfile
